steps:
  -   id: 'Run docker-compose'
      name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
      args: ['-f','docker-compose.yaml','up','-d','--build']

  -   id: 'Show docker-php-entrypoint content'
      name: 'gcr.io/cloud-builders/docker'
      args: ['exec','-t','moodle','cat','/usr/local/bin/docker-php-entrypoint']